### ISSUE TITLE
I got this issue, can you tell me how to fix it?

### ISSUE THREAD

**Issue by stvle131** [Joshua-Oladeji/GingerBread#1]
Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getPair(address,address)", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.0)
    at Logger.makeError (H:\abr\GingerBread\node_modules\@ethersproject\logger\lib\index.js:233:21)
    at Logger.throwError (H:\abr\GingerBread\node_modules\@ethersproject\logger\lib\index.js:242:20)
    at Interface.decodeFunctionResult (H:\abr\GingerBread\node_modules\@ethersproject\abi\lib\interface.js:382:23)
    at Contract.<anonymous> (H:\abr\GingerBread\node_modules\@ethersproject\contracts\lib\index.js:395:56)
    at step (H:\abr\GingerBread\node_modules\@ethersproject\contracts\lib\index.js:48:23)
    at Object.next (H:\abr\GingerBread\node_modules\@ethersproject\contracts\lib\index.js:29:53)
    at fulfilled (H:\abr\GingerBread\node_modules\@ethersproject\contracts\lib\index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: null,
  code: 'CALL_EXCEPTION',
  method: 'getPair(address,address)',
  errorArgs: null,
  errorName: null,
  errorSignature: null,

**Comment by JO-OLADEJI** [comment]
Sure man. So according to Ethers docs, "This error occurs when a call or transaction is used to interact with the blockchain reverts (via revert, require, et cetera)". So there needs to be proper handling of errors in the code. But if you view the tx hash logged on the console alongside this error, or you check the blockchain for the transactions, the error should be similar to `Pangolin: insufficient_liquidity`. My hypothesis for this is that other bots are faster and take advantage of the opportunity before Gingerbread bakes.

**Comment by stvle131** [comment]
thanks, so better to buy another node like chainstack or quicknode?
I purchased the quicknode but they said: 
```
H:\abr\GingerBread\node_modules\@ethersproject\logger\lib\index.js:233
        var error = new Error(message);
                    ^

Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.1)
    at Logger.makeError (H:\abr\GingerBread\node_modules\@ethersproject\logger\lib\index.js:233:21)
    at Logger.throwError (H:\abr\GingerBread\node_modules\@ethersproject\logger\lib\index.js:242:20)
    at JsonRpcProvider.<anonymous> (H:\abr\GingerBread\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:517:54)
    at step (H:\abr\GingerBread\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:48:23)
    at Object.throw (H:\abr\GingerBread\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:29:53)
    at rejected (H:\abr\GingerBread\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
```only work with the speednode from moralis

**Comment by stvle131** [comment]
execution reverted: Pangolin: INSUFFICIENT_LIQUIDITY
yes, i tried the node from chainstack but still slower than other bot, by the way, your code so friendly and helped me to understand a lot.

Hope you can upgrade it with so we can launch with the speed of light!
thanks
