### ISSUE TITLE
Can't run with Quicknode Archive Mode

### ISSUE THREAD

**Issue by stvle131** [Joshua-Oladeji/GingerBread#2]
I got this error when replace the moralis speed node with quicknode archive node. Please let me know how to fix this

```
H:\abr\GingerBread\node_modules\@ethersproject\logger\lib\index.js:233
        var error = new Error(message);
                    ^

Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.6.1)
    at Logger.makeError (H:\abr\GingerBread\node_modules\@ethersproject\logger\lib\index.js:233:21)
    at Logger.throwError (H:\abr\GingerBread\node_modules\@ethersproject\logger\lib\index.js:242:20)
    at JsonRpcProvider.<anonymous> (H:\abr\GingerBread\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:517:54)
    at step (H:\abr\GingerBread\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:48:23)
    at Object.throw (H:\abr\GingerBread\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:29:53)
    at rejected (H:\abr\GingerBread\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'could not detect network',
  code: 'NETWORK_ERROR',
  event: 'noNetwork'
```

**Comment by JO-OLADEJI** [comment]
### Possible Fixes
- Make sure your RPC URL is for avalanche c-chain.
- Make sure your RPC URL is functional

**Comment by stvle131** [comment]
thanks fixed, waiting for profit now :))
